In [1]:
#import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Dataset
from sklearn.datasets import load_iris

#For Model- algorithm
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

#For Performance Metrics
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [2]:
dataset = load_iris()

In [3]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [4]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

#Convert Data Into Dataframe

In [5]:
df = pd.DataFrame(dataset.data,columns=dataset.feature_names)
df.head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [6]:
#Add Target Column in dataframe.
df['target']= dataset.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [7]:
dataset.target #here 3 Classes available in target class

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

**We apply here both binary and multiclass classification.**

In [8]:
#For Firstly Binary Classification we get only 0 and 1.
df_binary=df[df['target']!=2]
df_binary.target.unique()

array([0, 1])

#Independant and Dependant Features

In [9]:
X = df_binary.iloc[:,:-1]
X[:5]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [10]:
y= df_binary.target
y[:5]

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

#Splitting Data

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=.20,random_state=42)

In [12]:
#Model fit
lr = LogisticRegression()

In [13]:
lr.fit(X_train,y_train)

LogisticRegression()

In [14]:
y_pred=lr.predict(X_test)

In [15]:
y_pred[:10]

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0])

In [16]:
y_test[:10]

83    1
53    1
70    1
45    0
44    0
39    0
22    0
80    1
10    0
0     0
Name: target, dtype: int64

In [17]:
#For check Probability of given classes
# use lr.predict_proba(X_test)

#Check Model - Performance Metrics

In [18]:
#Confusion Matrix
cm = confusion_matrix(y_pred,y_test)
cm

array([[12,  0],
       [ 0,  8]])

In [19]:
#Accuracy Matrix
print("Accuracy Score = ",accuracy_score(y_pred,y_test)*100)

Accuracy Score =  100.0


In [20]:
#Classification Report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



#Hyperparameter Tuning

In [21]:
#GridSearchCV
from sklearn.model_selection import GridSearchCV

In [22]:
#For unwanted warnings
import warnings
warnings.filterwarnings('ignore')

In [23]:
parameters = {'penalty':('l1','l2','elastinet',None),'C':[1,10,20]}

In [24]:
clf = GridSearchCV(lr,param_grid=parameters,cv=5)

In [25]:
#Splitting of Train data to validation data
clf.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20],
                         'penalty': ('l1', 'l2', 'elastinet', None)})

In [26]:
clf.best_params_

{'C': 1, 'penalty': 'l2'}

In [27]:
lr1 = LogisticRegression(C=1,penalty='l2')

In [28]:
lr1.fit(X_train,y_train)

LogisticRegression(C=1)

In [29]:
y_pred1 = lr1.predict(X_test)

In [30]:
print("Confusion Matrix: ")
print(confusion_matrix(y_pred1,y_test))

print("Accuracy Score : ",accuracy_score(y_pred1,y_test)*100)

print("Classification Report :")
print(classification_report(y_pred1,y_test))

Confusion Matrix: 
[[12  0]
 [ 0  8]]
Accuracy Score :  100.0
Classification Report :
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



#RandomizedSearchCV Hyperparameter Tuning

In [31]:
from sklearn.model_selection import RandomizedSearchCV

In [32]:
random_lr = RandomizedSearchCV(LogisticRegression(),param_distributions=parameters,cv=5)

In [33]:
random_lr.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [1, 10, 20],
                                        'penalty': ('l1', 'l2', 'elastinet',
                                                    None)})

In [34]:
random_lr.best_params_

{'penalty': None, 'C': 10}

In [39]:
lr2 = LogisticRegression(C=10,penalty=None)

In [40]:
lr2.fit(X_train,y_train)

LogisticRegression(C=10, penalty=None)

In [41]:
y_pred2 = lr2.predict(X_test)

In [42]:
print("Confusion Matrix: ")
print(confusion_matrix(y_pred2,y_test))

print("Accuracy Score : ",accuracy_score(y_pred2,y_test)*100)

print("Classification Report :")
print(classification_report(y_pred2,y_test))

Confusion Matrix: 
[[12  0]
 [ 0  8]]
Accuracy Score :  100.0
Classification Report :
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

