In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
s = pd.Series(['10','20','30'])
s

0    10
1    20
2    30
dtype: object

In [3]:
s.astype(int)+100 #astype to change datatype 'str' into 'int' or any and add new data

0    110
1    120
2    130
dtype: int64

# **What is need of Preprocessing data**
~ **Real world data generally contains noises,missing values,and maybe in an unusable format which cannot be directly used for ML models.                    
 ~ Data preprocessing is required task for cleanning data and making it suitable for a ML models which also increases the accuracy and efficiency of a ML
  models**                                                                        
 **It involves Belown Steps:**                                                   
1.    Finding missing data
2.    Encoding  Categorical data
3.    Splitting  dataset into training and testing set (80% / 20%)
4.    Feature Scaling



In [4]:
#data
data = [['India',np.nan,68000.0],
        ['France',43.0,45000.0],
        [np.nan,30.0,54000.0],
        ['France',48.0,65000.0],
        ['Germany',40.0,np.nan],
        ['India',35.0,58000.0],
        ['Germany',np.nan,53000.0],
        ['France',49.0,79000.0],
        ['India',50.0,88000.0],
        [np.nan,37.0,np.nan]]
data

[['India', nan, 68000.0],
 ['France', 43.0, 45000.0],
 [nan, 30.0, 54000.0],
 ['France', 48.0, 65000.0],
 ['Germany', 40.0, nan],
 ['India', 35.0, 58000.0],
 ['Germany', nan, 53000.0],
 ['France', 49.0, 79000.0],
 ['India', 50.0, 88000.0],
 [nan, 37.0, nan]]

In [5]:
#Convert data into dataframe
df = pd.DataFrame(data)
df

0     1        2
0    India   NaN  68000.0
1   France  43.0  45000.0
2      NaN  30.0  54000.0
3   France  48.0  65000.0
4  Germany  40.0      NaN
5    India  35.0  58000.0
6  Germany   NaN  53000.0
7   France  49.0  79000.0
8    India  50.0  88000.0
9      NaN  37.0      NaN

#Assignment Convert above data into csv file And check what happens with NaN values

In [47]:
df1 = df.to_csv('abc.csv', index=False,header=True)
df1

In [66]:
df1 = pd.read_csv('abc.csv')

new_columns ={'0':'country','1':'Age','2':'salary'}
df1.rename(columns=new_columns,inplace=True)
df1.columns

Index(['country', 'Age', 'salary'], dtype='object')

In [68]:
df1

country   Age   salary
0    India   NaN  68000.0
1   France  43.0  45000.0
2      NaN  30.0  54000.0
3   France  48.0  65000.0
4  Germany  40.0      NaN
5    India  35.0  58000.0
6  Germany   NaN  53000.0
7   France  49.0  79000.0
8    India  50.0  88000.0
9      NaN  37.0      NaN

In [69]:
#check null Values
df1.isna().sum()

country    2
Age        2
salary     2
dtype: int64

#Assignment : check Library misssingno
#plot the NaN present in your dataset

In [70]:
df1

country   Age   salary
0    India   NaN  68000.0
1   France  43.0  45000.0
2      NaN  30.0  54000.0
3   France  48.0  65000.0
4  Germany  40.0      NaN
5    India  35.0  58000.0
6  Germany   NaN  53000.0
7   France  49.0  79000.0
8    India  50.0  88000.0
9      NaN  37.0      NaN

In [ ]:
df.to

In [7]:
#assignment

#**Way to Handle Missing Data:**
**There is Mainly two ways to handle misssing data, which are:**                                           
**~ By Deleting the particular rows: The first ways is used to commmonly deal with null values in this way,we just deletethe specific rows or columns which consists of null values.**
**but this way is not so efficient and removing data may lead to loss of informantion which will not give the accurate output.**                      
**~ By Calulating the mean: In this way, we will calculate the mean of that particular column and rows which contains any missing values and will put it on the place of mising value.**
**this stategy is useful for the feature which have numeric data such as age,salary,year,etc. Here we will use this approach**



In [8]:
#using pandas which options are available to fillthe missing values/data.
#ffill/pad , backfill/bfill
#fillna()
#dropna()

In [71]:
df1.fillna('missing')

country      Age   salary
0    India  missing  68000.0
1   France     43.0  45000.0
2  missing     30.0  54000.0
3   France     48.0  65000.0
4  Germany     40.0  missing
5    India     35.0  58000.0
6  Germany  missing  53000.0
7   France     49.0  79000.0
8    India     50.0  88000.0
9  missing     37.0  missing

In [75]:
#only use first column to fill missing values.
df1.iloc[:,1].fillna('missing')

0    missing
1       43.0
2       30.0
3       48.0
4       40.0
5       35.0
6    missing
7       49.0
8       50.0
9       37.0
Name: Age, dtype: object

In [77]:
df1.salary

0    68000.0
1    45000.0
2    54000.0
3    65000.0
4        NaN
5    58000.0
6    53000.0
7    79000.0
8    88000.0
9        NaN
Name: salary, dtype: float64

In [81]:
df.iloc[:,2].fillna(method='ffill') #ffill()/pad() for forward filling

0    68000.0
1    45000.0
2    54000.0
3    65000.0
4    65000.0
5    58000.0
6    53000.0
7    79000.0
8    88000.0
9    88000.0
Name: 2, dtype: float64

In [79]:
df1.Age

0     NaN
1    43.0
2    30.0
3    48.0
4    40.0
5    35.0
6     NaN
7    49.0
8    50.0
9    37.0
Name: Age, dtype: float64

In [12]:
df.iloc[:,1].fillna(method='bfill') #backfill()/bfill() for backward filling

0    43.0
1    43.0
2    30.0
3    48.0
4    40.0
5    35.0
6    49.0
7    49.0
8    50.0
9    37.0
Name: 1, dtype: float64

In [86]:
df1.country

0      India
1     France
2        NaN
3     France
4    Germany
5      India
6    Germany
7     France
8      India
9        NaN
Name: country, dtype: object

In [87]:
df1

country   Age   salary
0    India   NaN  68000.0
1   France  43.0  45000.0
2      NaN  30.0  54000.0
3   France  48.0  65000.0
4  Germany  40.0      NaN
5    India  35.0  58000.0
6  Germany   NaN  53000.0
7   France  49.0  79000.0
8    India  50.0  88000.0
9      NaN  37.0      NaN

In [83]:
df1['country'].value_counts()

India      3
France     3
Germany    2
Name: country, dtype: int64

#**SimpleImputer**

In [14]:
from sklearn.impute import SimpleImputer
#handling missing data(replacing missing data with mean values in respective column)

#create a object for call SimpleImputer
si = SimpleImputer()
#other missing Examples : -999 -99 -1 -111 NA

'''
  **The Imputation Strategy**

  ~ If "mean", then replace missing values using the mean along each colummn.Can be used with numeric data.                             
  ~ If "median", then replace missing values using the median along each colummn.Can be used with numeric data.                            
  ~ If "most_frequent", then replace missing values using the most frequent value along each colummn.Can be used with strings or numeric data.
    if there is more than one such value, only the smallest is returned.  
  ~ If "constant", then replace missing values with fill values.Can be used with strings or numeric data.
'''

In [88]:
#fitting imputer object to the independent variable X.
ndf =df1.select_dtypes(exclude='object')
ndf

Age   salary
0   NaN  68000.0
1  43.0  45000.0
2  30.0  54000.0
3  48.0  65000.0
4  40.0      NaN
5  35.0  58000.0
6   NaN  53000.0
7  49.0  79000.0
8  50.0  88000.0
9  37.0      NaN

In [16]:
#traing
si.fit(ndf)

SimpleImputer()

In [17]:
si.missing_values

nan

In [18]:
si.n_features_in_

2

In [19]:
si.strategy

'mean'

In [20]:
#replacing missing data with the calculated mean value using transform
si.transform(ndf)

array([[4.150e+01, 6.800e+04],
       [4.300e+01, 4.500e+04],
       [3.000e+01, 5.400e+04],
       [4.800e+01, 6.500e+04],
       [4.000e+01, 6.375e+04],
       [3.500e+01, 5.800e+04],
       [4.150e+01, 5.300e+04],
       [4.900e+01, 7.900e+04],
       [5.000e+01, 8.800e+04],
       [3.700e+01, 6.375e+04]])

In [21]:
ndf.mean()

1       41.5
2    63750.0
dtype: float64

In [22]:
#if we want to perform fit and transform together
si.fit_transform(ndf)

array([[4.150e+01, 6.800e+04],
       [4.300e+01, 4.500e+04],
       [3.000e+01, 5.400e+04],
       [4.800e+01, 6.500e+04],
       [4.000e+01, 6.375e+04],
       [3.500e+01, 5.800e+04],
       [4.150e+01, 5.300e+04],
       [4.900e+01, 7.900e+04],
       [5.000e+01, 8.800e+04],
       [3.700e+01, 6.375e+04]])

#**Encoding the Categorical data :**

*   Categorical data is data which has some categories such as,Country
*   Since ML Models completely works on mathematics and numbers, but if our dataset would have categorical variable, then it may create trouble while building model. So it is neccessary to encode this categorical variables into numbers.




In [90]:
df1['country']

0      India
1     France
2        NaN
3     France
4    Germany
5      India
6    Germany
7     France
8      India
9        NaN
Name: country, dtype: object

In [91]:
df1['country'].unique()

array(['India', 'France', nan, 'Germany'], dtype=object)

#**Categorical data is of 2 types**
  ~   Nominal Data(where sequence order does not matter)               
      ex : Male/Females, Countrynames, VehicleNames, ObjectNames, ColorNames.                      
  ~   Ordinal Data(Where sequence order matters)
      ex : Result, Rank, Ratings, EducationalLevel

In [25]:
#using replace
#using map

#**sklearn.preprocessing**
**Label Encoder**

In [26]:
from sklearn.preprocessing import LabelEncoder

In [27]:
lb = LabelEncoder()

In [92]:
lb.fit_transform(df1['country'])

array([2, 0, 3, 0, 1, 2, 1, 0, 2, 3])

In [93]:
df1['country'].values

array(['India', 'France', nan, 'France', 'Germany', 'India', 'Germany',
       'France', 'India', nan], dtype=object)

In [30]:
lb.classes_

array(['France', 'Germany', 'India', nan], dtype=object)

#**New Data**

In [94]:
g = pd.DataFrame({'gender':['male','female','female','male','male','female'],
                    'cat':['A','A','A','B','C','C']})

In [33]:
lb2 = LabelEncoder()

In [34]:
lb2.fit(g['gender'])

LabelEncoder()

In [35]:
lb2.transform(g.gender)

array([1, 0, 0, 1, 1, 0])

In [36]:
lb2.classes_

array(['female', 'male'], dtype=object)

In [96]:
lb2.fit(g['cat'])

LabelEncoder()

In [97]:
lb2.transform(g.cat)

array([0, 0, 0, 1, 2, 2])

In [98]:
lb2.classes_

array(['A', 'B', 'C'], dtype=object)